#!/usr/bin/env bash
# Build a thin .app launcher in ~/Applications that restarts the
# blurt LaunchAgent when clicked.
#
#   ./make-app.sh
#
# The .app is just a shell-script wrapper over `service.sh restart` —
# no bundled Python, no extra dependencies. Re-run if the repo moves.

set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
app_name="Blurt"
app_dir="$HOME/Applications/$app_name.app"
bundle_id="local.blurt.launcher"

[[ -x "$here/service.sh" ]] || { echo "error: service.sh not found at $here" >&2; exit 1; }

mkdir -p "$HOME/Applications"
rm -rf "$app_dir"
mkdir -p "$app_dir/Contents/MacOS" "$app_dir/Contents/Resources"

cat > "$app_dir/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>$app_name</string>
    <key>CFBundleIdentifier</key>
    <string>$bundle_id</string>
    <key>CFBundleName</key>
    <string>$app_name</string>
    <key>CFBundleDisplayName</key>
    <string>$app_name</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <!-- Suppress Dock icon: this is a launcher that exits immediately. -->
    <key>LSUIElement</key>
    <true/>
</dict>
</plist>
EOF

cat > "$app_dir/Contents/MacOS/$app_name" <<EOF
#!/bin/bash
# Auto-generated by make-app.sh — do not edit.
exec "$here/service.sh" restart
EOF
chmod +x "$app_dir/Contents/MacOS/$app_name"

# Make Finder pick up the new bundle immediately.
touch "$app_dir"

echo "created $app_dir"
echo "  -> restarts LaunchAgent at $here"
